#winget programs
winget install --id=Microsoft.VCRedist.2005.x64 -e -h ; winget install --id=Microsoft.VCRedist.2005.x86 -e -h ; winget install --id=Microsoft.VCRedist.2008.x86 -e -h ; winget install --id=Microsoft.VCRedist.2008.x64 -e -h ; winget install --id=Microsoft.VCRedist.2010.x64 -e -h ; winget install --id=Microsoft.VCRedist.2010.x86 -e -h ; winget install --id=Microsoft.VCRedist.2012.x64 -e -h ; winget install --id=Microsoft.VCRedist.2012.x86 -e -h ; winget install --id=Microsoft.VCRedist.2013.x86 -e -h ; winget install --id=Microsoft.VCRedist.2013.x64 -e -h ; winget install --id=Microsoft.VCRedist.2015+.x64 -e -h ; winget install --id=Microsoft.VCRedist.2015+.x86 -e -h ; winget install --id=Microsoft.PowerShell -e -h ; winget install --id=BellSoft.LibericaJDK.8 -e -h ; winget install --id=AdoptOpenJDK.OpenJDK.16 -e -h ; winget install --id=BellSoft.LibericaJDK.17 -e -h ; winget install --id=BellSoft.LibericaJDK.18 -e -h ; winget install --id=Git.Git -e -h ; winget install --id=7zip.7zip -e -h ; winget install --id=Notepad++.Notepad++ -e -h ; winget install --id=Ditto.Ditto -e -h ; winget install --id=DuongDieuPhap.ImageGlass -e -h ; winget install --id=VideoLAN.VLC -e -h ; winget install --id=SumatraPDF.SumatraPDF -e -h ; winget install --id=ShareX.ShareX -e -h ; winget install --id=voidtools.Everything -e -h ; winget install --id=HandBrake.HandBrake -e -h ; winget install --id=Logitech.GHUB -e -h ; winget install --id=WinDirStat.WinDirStat -e -h ; winget install --id=RevoUninstaller.RevoUninstaller -e -h ; winget install --id=CrystalDewWorld.CrystalDiskInfo -e -h ; winget install --id=CrystalDewWorld.CrystalDiskMark -e -h ; winget install --id=Oracle.VirtualBox -e -h ; winget install --id=REALiX.HWiNFO -e -h ; winget install --id=Google.AndroidStudio -e -h ; winget install --id=CPUID.CPU-Z -e -h ; winget install --id=TechPowerUp.GPU-Z -e -h ; winget install --id=TechPowerUp.NVCleanstall -e -h ; winget install --id=BitSum.ProcessLasso -e -h ; winget install --id=GIMP.GIMP -e -h ; winget install --id=eloston.ungoogled-chromium -e -h ; winget install --id=Valve.Steam -e -h ; winget install --id=EpicGames.EpicGamesLauncher -e -h ; winget install --id=Spotify.Spotify -v "1.2.12.902.g1924b088" -e -h ; winget install --id=StrawberryMusicPlayer.Strawberry -e -h ; winget install --id=Discord.Discord -e -h ; winget install --id=OBSProject.OBSStudio -e -h ; winget install --id=Obsidian.Obsidian -e -h ; winget install --id=VSCodium.VSCodium -e -h ; winget install --id=jely2002.youtube-dl-gui -e -h ; winget install --id=Bitwarden.Bitwarden -e -h ; winget install --id=Autodesk.DesktopApp -e -h ; winget install --id=Unigine.HeavenBenchmark -e -h ; winget install --id=flux.flux -e -h ; winget install --id=OO-Software.ShutUp10 -e -h ; winget install --id=Rufus.Rufus -e -h ; winget install --id=RiotGames.Valorant.NA -e -h ; winget install --id=VB-Audio.VoiceMeeterBanana -e -h ; winget install --id=PrismLauncher.PrismLauncher -e -h# make dirs for portable programs

mkdir '$HOME\Documents\Portable Programs'

#download and move portables to folder 
curl https://www.hwinfo.com/files/GenericLogViewer/GenericLogViewer_v6.4.zip -o GLV.zip; Expand-Archive GLV.zip "$HOME\Documents\Portable Programs\Generic Log Viewer" ; Remove-Item GLV.zip
curl https://github.com/pbatard/rufus/releases/download/v4.0/rufus-4.0.exe -L -O -J ; mv rufus-4.0.exe "$HOME\Documents\Portable Programs\"
curl https://installer.maxon.net/cinebench/CinebenchR23.zip -o CinebenchR23.zip ; Expand-Archive CinebenchR23.zip "$HOME\Documents\Portable Programs\CinebenchR23" ; Remove-Item CinebenchR23.zip
curl https://www.mersenne.org/download/software/v30/30.8/p95v308b17.win64.zip -o Prime95.zip ; Expand-Archive Prime95.zip "$HOME\Documents\Portable Programs\Prime95" ; Remove-Item Prime95.zip
curl https://www.wagnardsoft.com/DDU/download/DDU%20v18.0.6.4.exe -o DDU.exe ; Start-Process -Wait DDU.exe ; Remove-Item DDU.exe
curl https://geeks3d.com/downloads/2023p/FurMark_1.34.0.0_Setup.exe -o Furmark.exe ; Start-Process -Wait Furmark.exe ; Remove-Item Furmark.exe

# creating shortcuts for portable programs
Set-ShortCut "$HOME\Documents\Portable Programs\rufus-4.0.exe" "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Rufus.lnk"
Set-ShortCut "$HOME\Documents\Portable Programs\CinebenchR23\Cinebench.exe" "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Cinebench R23.lnk"
Set-ShortCut "$HOME\Documents\Portable Programs\Prime95\prime95.exe" "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Prime 95.lnk"
Set-ShortCut "$HOME\Documents\Portable Programs\DDU v18.0.6.4\Display Driver Uninstaller.exe" "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Display Driver Uninstaller.lnk"
Set-ShortCut "$HOME\Documents\Portable Programs\Generic Log Viewer\GenericLogViewer.exe" "%ProgramData%\Microsoft\Windows\Start Menu\Programs\Generic Log Viewer.lnk"
